// <auto-generated />
using CoreTraining.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace CoreTraining.Migrations
{
    [DbContext(typeof(CodingClubDbContext))]
    partial class CodingClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CoreTraining.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Caption");

                    b.Property<int?>("CategoryID");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("PublisherID");

                    b.Property<string>("Slug");

                    b.Property<string>("Title");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("CoreTraining.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Slug");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CoreTraining.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.Property<string>("avatar");

                    b.Property<string>("slug");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreTraining.Models.Article", b =>
                {
                    b.HasOne("CoreTraining.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryID");

                    b.HasOne("CoreTraining.Models.User", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherID");
                });
#pragma warning restore 612, 618
        }
    }
}
